import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        tertiary: '#852b00',
        'secondary-fixed': '#85f8c4',
        'surface-container-highest': '#d9e3f4',
        'outline-variant': '#c3c5d7',
        'on-primary-container': '#d4dcff',
        'primary-fixed': '#dbe1ff',
        'surface-container-high': '#dfe9fa',
        'on-secondary-fixed-variant': '#005137',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#ffd4c5',
        background: '#f8f9ff',
        'surface-variant': '#d9e3f4',
        'on-background': '#121c28',
        'on-primary': '#ffffff',
        'primary-container': '#1a56db',
        'surface-tint': '#1353d8',
        'on-surface': '#121c28',
        'error-container': '#ffdad6',
        outline: '#737686',
        'on-primary-fixed-variant': '#003dab',
        'on-surface-variant': '#434654',
        'primary-fixed-dim': '#b5c4ff',
        'on-secondary-container': '#00714e',
        'on-tertiary-fixed': '#380d00',
        'tertiary-container': '#ad3b00',
        'on-secondary': '#ffffff',
        'surface-container': '#e5eeff',
        'surface-dim': '#d1dbec',
        error: '#ba1a1a',
        'surface-container-low': '#eef4ff',
        'inverse-surface': '#27313e',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#ffb59a',
        primary: '#003fb1',
        'on-tertiary-fixed-variant': '#802a00',
        'on-secondary-fixed': '#002114',
        'on-error': '#ffffff',
        secondary: '#006c4a',
        'secondary-container': '#82f5c1',
        'surface-bright': '#f8f9ff',
        surface: '#f8f9ff',
        'tertiary-fixed': '#ffdbcf',
        'on-error-container': '#93000a',
        'inverse-primary': '#b5c4ff',
        'on-primary-fixed': '#00174d',
        'secondary-fixed-dim': '#68dba9',
        'inverse-on-surface': '#eaf1ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '320px',
        base: '4px',
        'container-max': '1440px',
        xl: '48px',
        sm: '16px',
        'preview-min-width': '500px',
        md: '24px',
        xs: '8px',
        lg: '32px',
      },
      fontFamily: {
        h1: ['Manrope', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        h2: ['Manrope', 'sans-serif'],
        'template-h1': ['Newsreader', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Manrope', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        h1: ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        h2: ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'template-h1': ['36px', { lineHeight: '1.1', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.25s ease forwards',
        shimmer: 'shimmer 1.5s infinite linear',
      },
    },
  },
  plugins: [],
} satisfies Config
